import { useState, useEffect, useRef } from 'react';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';

gsap.registerPlugin(ScrollTrigger);

const experiences = {
  'Sinarmas Multiartha': {
    role: 'Data Scientist',
    company: 'Sinarmas Multiartha',
    date: 'JUL 2022 - PRESENT',
    points: [
      'Delivered AI workflows across use cases such as compliance, customer services, human resource processes.',
      'Expert in data visualization tools like Tableau and Superset to create interactive dashboards for stakeholders.',
      'Accountable in ETL processes using Python and SQL to ensure data accuracy and reliability for analysis and reporting.'
    ]
  },
  'Outlier': {
    role: 'Freelance AI Mathematics Trainer',
    company: 'Outlier',
    date: 'JUL 2024 - SEP 2024',
    points: [
      'Assessed factuality and relevance of mathematics text produced by AI models.',
      'Crated questions and answers related to mathematics field of expertise without AI.',
      'Evaluated and ranked mathematics responses generated by AI models.' 
    ]
  },
  'Mathematics Tutor': {
    role: 'Mathematics Tutor',
    company: 'Freelance',
    date: 'JAN 2024 - DEC 2024',
    points: [
      'Provided one-on-one tutor in undergraduate-level mathematics, especially in financial mathematics and business statistics.',
      'Mentored students to improve their problem-solving skills and conceptual understanding.',
      'Designed personalized learning plans to improve student\'s performance and confidence in mathematics.' 
    ]
  },
  'Assistant Lecturer': {
    role: 'Assistant Lecturer',
    company: 'Universitas Pelita Harapan',
    date: 'AUG 2018 - JUL 2021',
    points: [
      'Taught across applied mathematics courses such as Statistics, Calculus, Linear Algebra, Advanced Financial Mathematics, Computer Applications (Excel, SPSS).',
      'Conducted tutorial sessions, graded assignments, and provided academic support to students.',
      'Guided students in problem-solving.' 
    ]
  }
};

const defaultCompany = 'Sinarmas Multiartha';

/**
 * Experience Section Component
 * Displays professional work history with interactive company selection
 */
function ExperienceSection() {
  const [activeCompany, setActiveCompany] = useState(defaultCompany);
  const currentExp = experiences[activeCompany];
  const contentRef = useRef(null);
  const companyListRef = useRef(null);
  const sectionRef = useRef(null);

  // Scroll-triggered animation on mount
  useEffect(() => {
    const ctx = gsap.context(() => {
      // Animate company list items when scrolled into view
      gsap.fromTo('.company-list li', 
        {
          opacity: 0,
          x: -30
        },
        {
          opacity: 1,
          x: 0,
          duration: 0.3,
          stagger: 0.1,
          ease: 'power2.out',
          scrollTrigger: {
            trigger: sectionRef.current,
            start: 'top 80%',
            toggleActions: 'play none none none'
          }
        }
      );

      // Animate initial content when scrolled into view
      gsap.from('.experience-content', {
        opacity: 0,
        y: 20,
        duration: 0.6,
        delay: 0.3,
        ease: 'power2.out',
        scrollTrigger: {
          trigger: sectionRef.current,
          start: 'top 80%',
          toggleActions: 'play none none none'
        }
      });
    }, sectionRef);

    return () => ctx.revert();
  }, []);

  // Animate content when company changes
  useEffect(() => {
    if (contentRef.current) {
      gsap.fromTo(
        contentRef.current,
        {
          opacity: 0,
          y: 20
        },
        {
          opacity: 1,
          y: 0,
          duration: 0.5,
          ease: 'power2.out'
        }
      );
    }
  }, [activeCompany]);

  return (
    <section id="experience" className="experience" ref={sectionRef}>
      <div className="experience-wrapper">
        <h1 className="hero-title" align="left">
          <span className="highlight">#</span> experience
        </h1>
        <div className="experience-container" ref={companyListRef}>
          {/* LEFT - Company List */}
          <ul className="company-list">
            {Object.keys(experiences).map((company) => (
              <li
                key={company}
                className={activeCompany === company ? 'active' : ''}
                onClick={() => setActiveCompany(company)}
              >
                {company.toUpperCase()}
              </li>
            ))}
          </ul>

          {/* RIGHT - Experience Details */}
          <div className="experience-content" ref={contentRef}>
            <h3 className="exp-role">
              {currentExp.role} <span className="exp-company">@ {currentExp.company}</span>
            </h3>
            <p className="exp-date">{currentExp.date}</p>

            <ul className="exp-points">
              {currentExp.points.map((text, i) => (
                <li key={i}>{text}</li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </section>
  );
}

export default ExperienceSection;
