import { useState, useRef, useEffect } from 'react';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import './ExperienceSection.css';

gsap.registerPlugin(ScrollTrigger);

const experienceGroups = [
  {
    label: 'Formal',
    items: {
      'Sinarmas Multiartha': {
        role: 'Data Scientist',
        company: 'Sinarmas Multiartha',
        date: 'JUL 2022 - PRESENT',
        points: [
          'Provided business insights and customer risk scoring models for cash loan and motorcycle credit applications. Both projects were run end-to-end, from ETL processes and EDA (Exploratory Data Analysis) to developing traditional machine learning models like XGBoost and Linear Regression.',
          'Delivered AI workflows across use cases such as compliance, customer services, human resource processes.',
          'Expert in data visualization tools like Tableau and Superset to create interactive dashboards for stakeholders.',
          'Accountable in ETL processes using Python and SQL to ensure data accuracy and reliability for analysis and reporting.'
        ]
      },
      'Assistant Lecturer': {
        role: 'Assistant Lecturer',
        company: 'Universitas Pelita Harapan',
        date: 'AUG 2018 - JUL 2021',
        points: [
          'Taught across applied mathematics courses such as Statistics, Calculus, Linear Algebra, Advanced Financial Mathematics, Computer Applications (Excel, SPSS).',
          'Conducted tutorial sessions, graded assignments, and provided academic support to students.',
          'Guided students in problem-solving.'
        ]
      }
    }
  },
  {
    label: 'Freelance',
    items: {
      'Traffic Simulation': {
        role: 'Simulation Engineer',
        company: 'Freelance',
        date: '2026',
        points: [
          'Developed mathematical formulas into traffic light optimization algorithms using OSMnx road network data across Connecticut and New Jersey, United States.',
          'Built a road traffic simulation running on peak-hour conditions with traffic density derived from road length, width, and other geometric features.',
          'Reduced 48 road metrics into a single optimization output to minimize overall traffic congestion.'
        ]
      },
      '100sheep.net': {
        role: 'Creator & Developer',
        company: '100sheep.net',
        date: '2026',
        points: [
          'Created and launched onehundredsheep, a church care management platform that helps pastors track attendance, manage cell groups, and follow up with members.',
          'Built a full-stack web application featuring QR code attendance, member statistics, role-based access, and CSV import — from concept to deployment.'
        ]
      },
      'Outlier': {
        role: 'AI Mathematics Trainer',
        company: 'Outlier',
        date: 'JUL 2024 - SEP 2024',
        points: [
          'Assessed factuality and relevance of mathematics text produced by AI models.',
          'Crafted questions and answers related to mathematics field of expertise without AI.',
          'Evaluated and ranked mathematics responses generated by AI models.'
        ]
      },
      'Mathematics Tutor': {
        role: 'Mathematics Tutor',
        company: 'Freelance',
        date: 'JAN 2024 - DEC 2024',
        points: [
          'Provided one-on-one tutor in undergraduate-level mathematics, especially in financial mathematics and business statistics.',
          'Mentored students to improve their problem-solving skills and conceptual understanding.',
          'Designed personalized learning plans to improve student\'s performance and confidence in mathematics.'
        ]
      }
    }
  },
  {
    label: 'Voluntary',
    items: {
      'Youth Ministry GKY BSD': {
        role: 'Head of Youth Ministry Organization',
        company: 'Youth Ministry at GKY BSD',
        date: '',
        points: [
          'Led monthly meetings for a group of 20 youths and other planned activities for ~100 church members.',
          'Planned and organized community service projects, educational workshops, and youth retreat events.',
          'Mentored 7-10 people on personal development and academic challenges.',
          'Coordinated with other leaders and volunteers to ensure successful program execution.'
        ]
      }
    }
  }
];

function ChevronIcon() {
  return (
    <svg
      className="exp-chevron"
      width="20"
      height="20"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="6 9 12 15 18 9" />
    </svg>
  );
}

function ExperienceCard({ item, isOpen, onToggle, hoveredId, onHover }) {
  const detailRef = useRef(null);
  const contentRef = useRef(null);

  useEffect(() => {
    if (!detailRef.current || !contentRef.current) return;
    const content = contentRef.current;

    if (isOpen) {
      const height = content.scrollHeight;
      gsap.fromTo(
        detailRef.current,
        { height: 0, opacity: 0 },
        { height, opacity: 1, duration: 0.4, ease: 'power2.out', onComplete: () => {
          detailRef.current.style.height = 'auto';
        }}
      );
    } else {
      const currentHeight = detailRef.current.offsetHeight;
      gsap.fromTo(
        detailRef.current,
        { height: currentHeight, opacity: 1 },
        { height: 0, opacity: 0, duration: 0.3, ease: 'power2.inOut' }
      );
    }
  }, [isOpen]);

  const isHovered = hoveredId === item.id;

  return (
    <div
      className={`exp-card ${isHovered || isOpen ? 'exp-card--active' : ''} ${isOpen ? 'exp-card--open' : ''}`}
      onMouseEnter={() => onHover(item.id)}
      onMouseLeave={() => onHover(null)}
    >
      <div className="exp-card__bracket exp-card__bracket--tl" />
      <div className="exp-card__bracket exp-card__bracket--br" />

      <button
        className="exp-card__header"
        onClick={onToggle}
        aria-expanded={isOpen}
      >
        <div className="exp-card__info">
          <h3 className="exp-card__title">
            {item.role} <span className="exp-card__at">@</span> <span className="exp-card__company">{item.company}</span>
          </h3>
          {item.date && (
            <p className="exp-card__date">{item.date}</p>
          )}
        </div>
        <ChevronIcon />
      </button>

      <div
        ref={detailRef}
        className="exp-card__detail"
        style={{ height: 0, opacity: 0, overflow: 'hidden' }}
      >
        <div ref={contentRef} className="exp-card__detail-inner">
          <ul className="exp-card__timeline">
            {item.points.map((text, i) => (
              <li key={i} className="exp-card__timeline-item">
                <span className="exp-card__timeline-dot" />
                <span className="exp-card__timeline-text">{text}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </div>
  );
}

function ExperienceSection() {
  const [openId, setOpenId] = useState(null);
  const [hoveredId, setHoveredId] = useState(null);
  const sectionRef = useRef(null);

  const handleToggle = (id) => {
    setOpenId((prev) => (prev === id ? null : id));
  };

  useEffect(() => {
    const ctx = gsap.context(() => {
      gsap.fromTo(
        '.exp-card, .exp-divider',
        { opacity: 0, y: 20 },
        {
          opacity: 1,
          y: 0,
          duration: 0.4,
          stagger: 0.06,
          ease: 'power2.out',
          scrollTrigger: {
            trigger: sectionRef.current,
            start: 'top 80%',
            toggleActions: 'play none none none',
          },
        }
      );
    }, sectionRef);

    return () => ctx.revert();
  }, []);

  return (
    <section id="experience" className="experience" ref={sectionRef}>
      <div className="experience-wrapper">
        <h1 className="hero-title" align="left">
          <span className="highlight">#</span> experience
        </h1>
        <div className="exp-list">
          {experienceGroups.map((group, gi) => (
            <div key={group.label} className="exp-group">
              {gi > 0 && (
                <div className="exp-divider">
                  <span className="exp-divider__line" />
                  <span className="exp-divider__label">{group.label}</span>
                  <span className="exp-divider__line" />
                </div>
              )}
              {gi === 0 && (
                <div className="exp-divider">
                  <span className="exp-divider__line" />
                  <span className="exp-divider__label">{group.label}</span>
                  <span className="exp-divider__line" />
                </div>
              )}
              {Object.entries(group.items).map(([key, item]) => (
                <ExperienceCard
                  key={key}
                  item={{ id: key, ...item }}
                  isOpen={openId === key}
                  onToggle={() => handleToggle(key)}
                  hoveredId={hoveredId}
                  onHover={setHoveredId}
                />
              ))}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

export default ExperienceSection;
